### ISSUE TITLE
Issues about the Pvalue input

### ISSUE THREAD

**Issue by Constantine-mty** [ajaynadig/TRADE#8]
Hello author, I found an issue when calling TRADE. It requires input of pvalue because the output of DESeq2 contains both pvalue and the corrected aj pvalue, which caused confusion for me. When setting parameters, should I input the original pvalue or aj pvalue. 

In addition, when I called univariable, it output information. 
`Fitting mixture model
Warning messages:
1: In check_args(mixcompdist, df, prior, optmethod, gridmult, sebetahat,  :
  Use of halfuniform without nullbiased prior can lead to misleading local false sign rates, and so is not recommended
2: In check_args(mixcompdist, df, prior, optmethod, gridmult, sebetahat,  :
  Use of halfuniform without nullbiased prior can lead to misleading local false sign rates, and so is not recommended
3: In check_args(mixcompdist, df, prior, optmethod, gridmult, sebetahat,  :
  Use of halfuniform without nullbiased prior can lead to misleading local false sign rates, and so is not recommended
4: In check_args(mixcompdist, df, prior, optmethod, gridmult, sebetahat,  :
  Use of halfuniform without nullbiased prior can lead to misleading local false sign rates, and so is not recommended
5: In check_args(mixcompdist, df, prior, optmethod, gridmult, sebetahat,  :
  Use of halfuniform without nullbiased prior can lead to misleading local false sign rates, and so is not recommended`
Although it does not affect the output of the result, I am not good at statistical knowledge and want to know what caused this and whether it will affect the correctness of the result

**Comment by Constantine-mty** [comment]
adj pavlue

**Comment by ajaynadig** [comment]
Hello, and thank you for your interest in the TRADE package.

For TRADE analysis, you should input the **pvalue**, rather than the adjusted p value. TRADE performs adjustment of p values internally, so it takes as input the raw, unadjusted p value. Please see the wiki for more details on how to prepare inputs for TRADE.

For the warning message, this is not a concern; I should probably find a way to suppress that warning. The original purpose of the ash package was to perform two steps: 1) infer the distribution of effect sizes, and then 2) shrink the observed effect sizes using that distribution as a prior (i.e. "empirical bayes"). In TRADE, we are only interested in 1), and not in 2), which means that we make slightly different choices in our statistical modelling.

In particular, ash includes a "null-biased" prior when performing 1), so that inferred distributions with a large point mass at zero are preferred. Stephens (2017) showed that this penalty term improves inference of the local false-sign rate, which is used to determine whether individual effects are non-zero.

In the case of TRADE analysis, our goal is not to make inferences about the significance of individual effects (although this is perhaps an interesting area to extend TRADE); rather, we simply want to estimate the underlying distribution of effect sizes as accurately as possible. With that in mind, we elected to remove the null-biased prior. As a result, ash warns us that local false sign rates may be miscalibrated; this may indeed be the case, but TRADE makes no use of those estimates.

I hope that clarifies these aspects of TRADE analysis--please let me know if any confusion remains.

**Comment by Constantine-mty** [comment]
Thank you, the issues with p-value and warning have been resolved.
I also look forward to adding a demo of DESeq2 differential analysis on GitHub when the article is officially published, because I did GATA1 differential analysis of k562 cell data based on the tutorial of Pertpy (a Python package), but the results are very different from yours. So I want to know how you specifically did the difference analysis steps

Of course, my issue has been resolved and can now be closed

**Comment by ajaynadig** [comment]
Hmm—after a quick look it seems as though Pertpy implements several different differential expression tools, including PyDESeq2. Can I ask which method you used?

I will upload a tutorial in the coming weeks. For now, you can find the details for how we ran DESeq2 in the methods section of our preprint, which is linked on the main page of the repository.

**Comment by Constantine-mty** [comment]
yes, I used the PyDESeq2 Method, And thank you again for your patient reply ！
